#ifndef PLATFORM_SERVICES_H
#define PLATFORM_SERVICES_H

#include "hal_data.h"
#include <stdint.h>

/* Keep 0 for the current single-core project. Set to 1 only in the CPU0
 * project generated by an RA FSP multicore Solution. */
#ifndef PLATFORM_SERVICES_MULTICORE
#define PLATFORM_SERVICES_MULTICORE (0)
#endif

typedef struct st_platform_touch
{
    uint16_t x;
    uint16_t y;
    uint8_t points;
    uint8_t down;
} platform_touch_t;

typedef struct st_platform_weight
{
    int16_t grams;
    int16_t raw;
    uint32_t frame_count;
    uint8_t valid;
} platform_weight_t;

typedef struct st_platform_health
{
    uint8_t multicore_enabled;
    uint8_t m33_online;
    uint8_t m85_seen_by_m33;
    uint8_t touch_ready;
    uint8_t touch_status;
    uint8_t touch_bus_levels;
    uint8_t weight_ready;
    uint16_t m33_tx_drops;
    uint16_t m85_tx_drops;
} platform_health_t;

fsp_err_t platform_services_init(void);
void platform_services_poll(void);
uint8_t platform_services_touch_read(platform_touch_t * touch);
void platform_services_weight_get(platform_weight_t * weight);
void platform_services_health_get(platform_health_t * health);
void platform_services_m85_heartbeat(uint32_t frame_count, uint32_t ceu_recoveries);

#if PLATFORM_SERVICES_MULTICORE
void platform_services_ipc_callback(ipc_callback_args_t * p_args);
#endif

#endif
